# Generated by Django 5.0.2 on 2024-02-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pinguino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('adoptado', models.BooleanField(default=False)),
                ('imagen', models.ImageField(upload_to='fotos')),
            ],
        ),
    ]
