# Generated by Django 5.0.1 on 2024-02-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_incidencias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incidencias',
            new_name='Incidencia',
        ),
    ]
