# Generated by Django 5.0.2 on 2024-02-28 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('lugar', models.CharField(max_length=50)),
                ('persona1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona1', to='parejas.persona')),
                ('persona2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona2', to='parejas.persona')),
            ],
        ),
    ]
