# Generated by Django 5.0.1 on 2024-01-29 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FrameWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creationDate', models.DateField()),
                ('languaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languajes.languaje')),
            ],
        ),
    ]
