# Generated by Django 5.0.1 on 2024-01-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languajes', '0002_alter_languaje_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='creationDate',
            field=models.IntegerField(),
        ),
    ]
